#!/usr/bin/env node
// D15 — the defend/attack balance sheet (doc 03 "defender pays CT, attacker pays in units"). For each calibration-castle
// scenario in reports/SIM-SAMPLE.json, it sets what the defender PAID (CT staked or fee, the burned share, the escrow the
// attacker can win) against what the attacker LOST (median sim units → soldiers → canon re-training CT from
// docs/03-military.md §3). Canon reports casualties in SOLDIERS (doc 09 §5 BattleResult.casualties), so the engine needs
// SOLDIERS_PER_SIM_UNIT, which has no canon value yet; the sheet is printed at several values (⚙ proposal 10).
//   node tools/living-world/balance_sheet.mjs [--out docs/living-world/reports/BALANCE-SHEET.md]
import fs from "node:fs";
const i = process.argv.indexOf("--out"), OUT = i > 0 ? process.argv[i + 1] : "docs/living-world/reports/BALANCE-SHEET.md", JOUT = OUT.replace(/\.md$/, ".json");
const SIM = JSON.parse(fs.readFileSync("docs/living-world/reports/SIM-SAMPLE.json", "utf8"));
const DF = JSON.parse(fs.readFileSync("data/living-world/defences.json", "utf8")), GU = JSON.parse(fs.readFileSync("data/living-world/guardians.json", "utf8"));
// D40: canon re-training cost from packages/shared/balance.json v2 (RE-SCALED ÷100), ct_units → CT (÷10,000).
// The docs/03 §3 table (2 / 10 CT per soldier) predates that re-scale and is NOT used.
const BAL = JSON.parse(fs.readFileSync("/home/user/cf-overworld/packages/shared/balance.json", "utf8"));
const trainCT = (cls) => BAL.units.trainCtUnitsPerSoldier[cls] / 10000;
export const RATIOS = [1, 5, 10, 20], PROPOSED_RATIO = 10;
// the harness attacker is ⅓ canon SIEGE, ⅔ line troops (INFANTRY); waves are INFANTRY too, so this is an upper bound on SIEGE share
const ctPerSoldier = (2 * trainCT("INFANTRY") + trainCT("SIEGE")) / 3;
const med = (a) => { const s = a.slice().sort((x, y) => x - y); return s[Math.floor((s.length - 1) / 2)]; };
const lvlCost = (u) => Array.from({ length: u.levels }, (_, l) => u.baseCT * DF.rating.levelCostGrowth ** l).reduce((a, b) => a + b, 0);
const fullStack = DF.upgrades.filter((u) => !u.estateOnly).reduce((n, u) => n + lvlCost(u), 0);
const kindMul = GU.kindMultiplier.KEEP;   // the calibration castle is tier 1 (a KEEP)
const DEF = {
  BASE: { paid: 0, burned: 0, escrow: 0, what: "Bare castle" },
  DEFENDED: { paid: fullStack, burned: fullStack * DF.stakeSplit.burn, escrow: fullStack * DF.stakeSplit.spoilsEscrow, what: "Full defence stack (every castle upgrade at max level, 7 days)" },
  F2: { paid: GU.forms["2"].feeCT * kindMul, burned: GU.forms["2"].feeCT * kindMul * GU.feeSplit.burn, escrow: GU.forms["2"].feeCT * kindMul * GU.feeSplit.bountyEscrow, what: "+ Form 2 Warden (stationing fee)" },
  F3: { paid: GU.forms["3"].feeCT * kindMul, burned: GU.forms["3"].feeCT * kindMul * GU.feeSplit.burn, escrow: GU.forms["3"].feeCT * kindMul * GU.feeSplit.bountyEscrow, what: "+ Form 3 Ascendant (stationing fee)" },
};
const r1 = (x) => Math.round(x * 1000) / 1000;   // D40: canon-scale CT needs finer rounding
const rows = Object.entries(DEF).map(([sc, d]) => {
  const runs = SIM.scenarios.filter((x) => x.scen === sc), lost = med(runs.map((x) => x.attackerDeaths)), sec = med(runs.map((x) => x.sec));
  return { scen: sc, what: d.what, defenderPaidCT: r1(d.paid), burnedCT: r1(d.burned), escrowCT: r1(d.escrow), medBreachSec: sec, attackerUnitsLost: lost,
    lossCT: Object.fromEntries(RATIOS.map((r) => [r, Math.round(lost * r * ctPerSoldier * 100) / 100])) };
});
const base = rows.find((r) => r.scen === "BASE");
for (const r of rows) {
  r.extraUnitsLost = r.attackerUnitsLost - base.attackerUnitsLost; r.extraSec = r.medBreachSec - base.medBreachSec;
  r.ctPerExtraUnitLost = r.extraUnitsLost > 0 ? r1(r.defenderPaidCT / r.extraUnitsLost) : null;   // what the defender pays per sim unit they make the attacker lose
  r.ctPerExtraMinute = r.extraSec > 0 ? r1(r.defenderPaidCT / (r.extraSec / 60)) : null;
}
const d = rows.find((r) => r.scen === "DEFENDED"), f2 = rows.find((r) => r.scen === "F2"), f3 = rows.find((r) => r.scen === "F3");
const findings = {
  defencesVsWarden: r1(d.ctPerExtraUnitLost / f2.ctPerExtraUnitLost),
  wardenBountyVsLosses: r1((f2.extraUnitsLost * PROPOSED_RATIO * ctPerSoldier) / f2.escrowCT),
  ascendantBountyVsLosses: r1((f3.extraUnitsLost * PROPOSED_RATIO * ctPerSoldier) / f3.escrowCT),
};
fs.writeFileSync(JOUT, JSON.stringify({ schema: "cf-living-world/balance-sheet@1", ctPerSoldier: r1(ctPerSoldier), ratios: RATIOS, proposedRatio: PROPOSED_RATIO, rows, findings }, null, 1) + "\n");
const f = (v) => (v == null ? "—" : Math.floor(v / 60) + ":" + String(v % 60).padStart(2, "0"));
const md = ["# Defend / attack balance sheet: CT paid vs units lost", "",
  `Generated by \`tools/living-world/balance_sheet.mjs\` from \`SIM-SAMPLE.json\` (calibration castle, threat 50, tier 1), \`defences.json\`, \`guardians.json\` and the canon re-training cost (\`packages/shared/balance.json\` v2 \`units.trainCtUnitsPerSoldier\`: INFANTRY ${trainCT("INFANTRY")} CT, SIEGE ${trainCT("SIEGE")} CT per soldier → **${r1(ctPerSoldier)} CT per soldier** for the harness's ⅓-siege mix).`, "",
  "Canon reports casualties in soldiers (`BattleResult.casualties`, doc 09 §5), so the engine needs a **soldiers-per-sim-unit** ratio. It has no canon value yet; the CT-equivalent columns show it at 1, 5, 10 (⚙ proposal) and 20.", "",
  "| Scenario | Defender pays (CT) | Of which burned | Attacker can win (CT) | Median breach | Attacker units lost | Loss in CT at ×1 / ×5 / **×10** / ×20 | Defender CT per extra attacker unit lost | Defender CT per extra minute held |", "|---|---|---|---|---|---|---|---|---|",
  ...rows.map((r) => `| ${r.what} | ${r.defenderPaidCT} | ${r.burnedCT} | ${r.escrowCT} | ${f(r.medBreachSec)} | ${r.attackerUnitsLost}${r.extraUnitsLost ? ` (+${r.extraUnitsLost})` : ""} | ${RATIOS.map((x) => (x === PROPOSED_RATIO ? `**${r.lossCT[x].toLocaleString("en")}**` : r.lossCT[x].toLocaleString("en"))).join(" / ")} | ${r.ctPerExtraUnitLost ?? "—"} | ${r.ctPerExtraMinute ?? "—"} |`), "",
  "## What the sheet says", "",
  `1. **Guardians are far cheaper than defences for the same pain.** A full defence stack costs the defender **${d.ctPerExtraUnitLost} CT per extra attacker unit lost**. A Form 2 Warden costs **${f2.ctPerExtraUnitLost} CT**, which is ${Math.round(findings.defencesVsWarden)}× cheaper. A Form 3 costs ${f3.ctPerExtraUnitLost} CT.`,
  "   - Part of that is by design: a Guardian's real price is the NFT itself (scarce, with a 24 h / 72 h cooldown, one per perch, one Ascendant per castle per week).",
  "   - Still, a " + GU.forms["2"].feeCT + " CT Warden imposing +" + f2.extraUnitsLost + " units of losses is the outlier.",
  `2. **The Guardian bounty doesn't pay for the fight it asks for.** At ×${PROPOSED_RATIO} soldiers per unit, the attacker's extra losses against a Warden are worth **${Math.round(findings.wardenBountyVsLosses)}×** the bounty they can win (${Math.round(findings.ascendantBountyVsLosses)}× for an Ascendant).`,
  "   - So nobody hunts a Guardian for the bounty alone. Guardian hunts need the castle itself as the prize, or a bigger escrow.",
  `3. **Defences buy force, not time.** The full stack adds only ${f(d.extraSec)} to the breach. That's doc 03's floor working as intended: a 1.5× defence-weighted attacker still breaks in under 12 min.`,
  `   - What the defender really buys is that the attacker must **bring 1.6× the army**. It's an entry price on the attacker's commitment, not on their losses (+${d.extraUnitsLost} units).`,
  "", "Owner call (`OWNER-DECISIONS.md` §5). Raising the fees alone can't close finding 2: even a ×3 Warden fee leaves the bounty about " + Math.round(findings.wardenBountyVsLosses / 3) + "× short. So the choice is about *what a Guardian hunt is for*:", "",
  "- **A (recommended):** the prize is the castle. The bounty is a trophy, not a wage. Raise the Warden fee " + GU.forms["2"].feeCT + " → " + 3 * GU.forms["2"].feeCT + " CT (still the cheapest pain, but ~" + Math.round(d.ctPerExtraUnitLost / (3 * GU.forms["2"].feeCT * kindMul / f2.extraUnitsLost)) + "× rather than ~" + Math.round(findings.defencesVsWarden) + "× cheaper than defences), and **say so in the feed** (\"the bounty is glory; the castle is the prize\").",
  "- **B:** the bounty is a wage. The region pool tops up a standing Guardian's escrow to ~25 % of the expected extra attacker losses. That needs a pool source and is a CT sink decision.",
  "- **C:** leave as is. ⚠ Wardens stay the dominant defence purchase by two orders of magnitude.", ""].join("\n");
fs.writeFileSync(OUT, md);
console.log(md.split("\n").slice(8, 14).join("\n"));
