#!/usr/bin/env node
// Living World D8 — export the castle POIs as CF's reserved world-elements layer: data/world-elements/<ZONE>.cf.json
// (docs/briefs/WORLD-ELEMENTS-OVERLAY.md on the overworld branch: point-only, open kind, read-time merge, ≤ 6/parcel).
// GUARDIAN_PERCH stays out (it sits inside the castle's own battle map, not on the world map).
//   node tools/living-world/export_cf_overlay.mjs [--out data/living-world/world-elements]
import fs from "node:fs";
import path from "node:path";
const args = Object.fromEntries(process.argv.slice(2).reduce((a, v, i, all) => (v.startsWith("--") ? a.concat([[v.slice(2), all[i + 1]]]) : a), []));
const OUT = args.out || "data/living-world/world-elements";
const CP = JSON.parse(fs.readFileSync("data/living-world/castle-pois.json", "utf8"));
const NAMES = { HARBOUR: "Harbour", AIRSHIP_DOCK: "Airship Dock", LANDING_SPOT: "Landing Spot", AIRDROP_ZONE: "Airdrop Zone", BARBARIAN_CAMP: "Barbarian Camp",
  MERCENARY_POST: "Mercenary Post", CARAVAN_WAYPOINT: "Caravan Waypoint", WILD_LAIR: "Lair", WAR_CAMP: "War Camp", SALVAGE_SITE: "Salvage Site", VENT: "Vent" };
const byZone = {};
for (const c of CP.byCastle) for (const p of c.pois) {
  if (p.lwKind === "GUARDIAN_PERCH") continue;
  const short = c.castleId.replace(new RegExp("^" + c.zone + "-"), "");
  const n = p.id.split(":").pop();
  (byZone[c.zone] ||= []).push({ id: `${c.zone}-CF-${short}-${p.lwKind}-${n}`, kind: p.lwKind, at: p.at,
    name: `${NAMES[p.lwKind] || p.lwKind}${p.monster ? " (" + p.monster.toLowerCase().replace(/_/g, " ") + ")" : ""}`,
    note: `Living-world Node of ${c.castleId} (threat ${p.threat})${p.anchorPoi ? " — on " + p.anchorPoi : ""}${p.parent ? " — lands for " + p.parent.split(":").slice(1).join(" ") : ""}`,
    loreRef: "etherfantasy-clashfront@claude/browser-moba-clashfont-gmiy7p docs/living-world/01-POI-CATALOGUE.md" });
}
fs.mkdirSync(OUT, { recursive: true });
let total = 0;
for (const z of Object.keys(byZone).sort()) {
  const els = byZone[z].sort((a, b) => (a.id < b.id ? -1 : 1)); total += els.length;
  fs.writeFileSync(path.join(OUT, `${z}.cf.json`), JSON.stringify({ _meta: { layer: "cf", zone: z, owner: "Clash Front living world (Agent C events layer)",
    note: "GENERATED by tools/living-world/export_cf_overlay.mjs from castle-pois.json — do not hand-edit; re-run the exporter.", coords: `zone svg coords (same frame as data/world-terrain/${z}.json)` }, elements: els }, null, 1) + "\n");
}
console.log(`cf overlay: ${total} elements in ${Object.keys(byZone).length} zones → ${OUT}`);
