#!/usr/bin/env node
// Living World D6e — archetype × ground sampling matrix (doc 02 §5.2). For every (archetype, ring tier, ground) cell
// that the seeders actually produce, draw N seeded POIs (fixed fnv1a order, no clock) and run each through the shared
// headless harness (sim_harness.mjs, real server/sim kernel). Each cell is judged against its tier band (doc 06 §2):
//   CASTLE ring (in-castle POIs)    → RAID band     6–12 min
//   FRONTIER / WILD (estate POIs)   → SKIRMISH band 3–6 min
//   node tools/living-world/sim_matrix.mjs [--n 4] [--out docs/living-world/reports/SIM-MATRIX.md]
import fs from "node:fs";
import { PA, pool, fnv1a, runOne, opts, terrainMods, TM } from "./sim_harness.mjs";
const args = Object.fromEntries(process.argv.slice(2).reduce((a, v, i, all) => (v.startsWith("--") ? a.concat([[v.slice(2), all[i + 1]]]) : a), []));
opts.TERRAIN = args.terrain === "off" ? false : args.terrain === "proposed" ? "proposed" : true;   // D14: canon terrain mods by ground (pass --terrain off for the flat baseline)
const N = +(args.n || 4), OUT = args.out || "docs/living-world/reports/SIM-MATRIX.md", JOUT = OUT.replace(/\.md$/, ".json");
export const BANDS = { CASTLE: { name: "RAID", lo: 360, hi: 720 }, FRONTIER: { name: "SKIRMISH", lo: 180, hi: 360 }, WILD: { name: "SKIRMISH", lo: 180, hi: 360 } };

const garrisoned = new Set(PA.archetypes.filter((a) => a.garrison.length).map((a) => a.lwKind));
const cells = new Map();
for (const p of pool) if (garrisoned.has(p.k)) { const key = `${p.k}|${p.ring}|${p.ground}`; if (!cells.has(key)) cells.set(key, []); cells.get(key).push(p); }
const med = (a) => { const s = a.slice().sort((x, y) => x - y); return s.length ? s[Math.floor((s.length - 1) / 2)] : null; };
const mmss = (v) => (v != null ? Math.floor(v / 60) + ":" + String(v % 60).padStart(2, "0") : "—");

const rows = [...cells.keys()].sort().map((key) => {
  const [k, ring, ground] = key.split("|"), all = cells.get(key), band = BANDS[ring];
  const picks = all.slice().sort((a, b) => fnv1a(a.id + "|pick") - fnv1a(b.id + "|pick")).slice(0, N);
  // D30 proposed mode: apply the proposed seed groundShift for SKY/UNDER (what a re-seed would produce), floor moving with it
  const shifted = opts.TERRAIN === "proposed" ? picks.map((p) => { const sh = TM.proposed.groundShift[p.ground] || 0, b = PA.threatBands[p.ring]; return sh ? { ...p, threat: Math.max(b.lo + sh, p.threat + sh) } : p; }) : picks;
  const r = shifted.map((p) => runOne(p)), b = r.filter((x) => x.breached), m = med(b.map((x) => x.sec));
  const breachRate = Math.round((100 * b.length) / r.length);
  const verdict = breachRate < 50 ? "HARD" : m < band.lo ? "SOFT" : m > band.hi ? "SLOW" : "ok";
  return { k, ring, ground, population: all.length, n: r.length, band: band.name, breachRate, medBreachSec: m, medThreat: med(shifted.map((p) => p.threat)), medAttackerDeaths: med(r.map((x) => x.attackerDeaths)), verdict };
});
const tally = rows.reduce((t, r) => ((t[r.verdict] = (t[r.verdict] || 0) + 1), t), {});
const popOut = rows.filter((r) => r.verdict !== "ok").reduce((n, r) => n + r.population, 0), popAll = rows.reduce((n, r) => n + r.population, 0);
fs.writeFileSync(JOUT, JSON.stringify({ schema: "cf-living-world/sim-matrix@1", kernel: "server/sim (deterministic)", terrain: opts.TERRAIN, nPerCell: N, bands: BANDS, tally, populationOutOfBand: popOut, population: popAll, rows }, null, 1) + "\n");

const md = ["# Headless-sim matrix — archetype × ring × ground vs the tier bands", "",
  `Generated by \`tools/living-world/sim_matrix.mjs\` (N = ${N} seeded POIs per cell, the shared \`sim_harness.mjs\` on the real \`server/sim\` kernel). Deterministic: re-running gives the same table.`, "",
  "Bands (doc 06 §2): in-castle POIs are **RAID** (6–12 min); frontier and wild POIs are **SKIRMISH** (3–6 min). Verdicts: `SOFT` falls before the band, `SLOW` after it, `HARD` means fewer than half the attacks breach within 12 min.", "",
  `**${rows.length} cells**: ${Object.entries(tally).map(([v, n]) => `${n} ${v}`).join(", ")}. Seeded POIs in out-of-band cells: **${popOut.toLocaleString("en")} of ${popAll.toLocaleString("en")}** (${Math.round((100 * popOut) / popAll)} %).`, "",
  "| Archetype | Ring | Ground | POIs seeded | n | Band | Breached | Median breach | Median threat | Median attacker losses | Verdict |", "|---|---|---|---|---|---|---|---|---|---|---|",
  ...rows.map((r) => `| ${r.k} | ${r.ring} | ${r.ground} | ${r.population.toLocaleString("en")} | ${r.n} | ${r.band} | ${r.breachRate} % | ${mmss(r.medBreachSec)} | ${r.medThreat} | ${r.medAttackerDeaths} | ${r.verdict === "ok" ? "ok" : "**" + r.verdict + "**"} |`), "",
  (opts.TERRAIN ? "Ground applies the canon terrain modifiers (`terrain-mods.json`, from cf-overworld doc 04: FOREST 0.95/1.05, RIDGE→HILLS 0.90/1.10, WATER→RIVER crossing 0.90/1.10; SKY and UNDER neutral until canon names them), as damage-taken multipliers on each side." : "Flat baseline (`--terrain off`): ground acts only through seeded threat."), "",
  "Tuning rule (doc 02 §5): an out-of-band cell is fixed in `poi-archetypes.json` (garrison, or the threat curve for that ring), never per map.", ""].join("\n");
fs.writeFileSync(OUT, md);
console.log(md.split("\n").slice(6, 7).join("\n"));
