#!/usr/bin/env node
// Living World D6 — headless-sim sampling of POI templates (doc 02 §5.2). Runs the REAL deterministic battle kernel
// (server/sim) on seeded POIs: the POI's threat scales the defending core, its garrison spawns as leashed defenders
// (team 1, kind "wild" → they hold ground), the neutral camps stay as third-party barbarians, and the attacker is the
// stock bot + minion waves. Measures breach (core down) within the 12-min floor (doc 03) and attacker losses.
// Deterministic: world seed = the POI's deckSeed / fnv1a(id); fixed dt; no clock.
//   node tools/living-world/sim_sample.mjs [--n 6] [--out docs/living-world/reports/SIM-SAMPLE.md]
import fs from "node:fs";
import { opts, PA, ARCH, pool, fnv1a, runOne, FLOOR_SEC, DT } from "./sim_harness.mjs";
const args = Object.fromEntries(process.argv.slice(2).reduce((a, v, i, all) => (v.startsWith("--") ? a.concat([[v.slice(2), all[i + 1]]]) : a), []));
const SQUAD_MUL = +(args.squadMul || 1.5), ONLY = args.only || null, DEF_MUL = +(args.defMul || 3);   // DEF_MUL: structure-HP calibration (D6b sweep: ×3 → a bare threat-50 castle breaches at ~9 min, mid 6–12 band)
const N = +(args.n || 6), OUT = args.out || "docs/living-world/reports/SIM-SAMPLE.md", JOUT = OUT.replace(/\.md$/, ".json");
Object.assign(opts, { SQUAD_MUL, DEF_MUL, G_HP: args.gHp ? +args.gHp : null });


const kindsWithGarrison = PA.archetypes.filter((a) => a.garrison.length).map((a) => a.lwKind).sort();
const results = [];
ARCH.CALIBRATION = { garrison: [] };   // threat 0, no garrison: the bare-structure baseline
kindsWithGarrison.unshift("CALIBRATION"); for (let i = 0; i < N; i++) pool.push({ id: "calib-" + i, k: "CALIBRATION", threat: 50 });   // a typical castle-band threat
for (const k of kindsWithGarrison.filter((k) => !ONLY || k === ONLY)) {
  const cands = pool.filter((p) => p.k === k).sort((a, b) => fnv1a(a.id + "|pick") - fnv1a(b.id + "|pick")).slice(0, N);
  for (const p of cands) results.push(runOne(p));
}
// doc 03 / doc 04 scenarios on the calibration castle (threat 50)
const SCEN = [];
for (const sc of ["BASE", "DEFENDED", "F2", "F3"]) for (let i = 0; i < N; i++) SCEN.push(runOne({ id: `scen-${sc}-${i}`, k: "CALIBRATION", threat: 50 }, sc));
const med = (a) => { const s = a.slice().sort((x, y) => x - y); return s.length ? s[Math.floor((s.length - 1) / 2)] : null; };
const rows = kindsWithGarrison.map((k) => {
  const r = results.filter((x) => x.k === k), b = r.filter((x) => x.breached);
  const row = { k, n: r.length, breachRate: r.length ? Math.round((100 * b.length) / r.length) : 0, medBreachSec: med(b.map((x) => x.sec)), medThreat: med(r.map((x) => x.threat)), medAttackerDeaths: med(r.map((x) => x.attackerDeaths)), defenderWins: r.filter((x) => x.defenderWon).length };
  row.flag = !r.length ? "NO SAMPLES" : row.breachRate < 50 ? "TOO HARD (most attacks fail the 12-min floor)" : row.breachRate === 100 && row.medBreachSec < 180 ? "TOO SOFT (falls in < 3 min, below the SKIRMISH band)" : "ok";
  return row;
});
fs.writeFileSync(JOUT, JSON.stringify({ schema: "cf-living-world/sim-sample@1", kernel: "server/sim (deterministic)", floorSec: FLOOR_SEC, nPerKind: N, rows, results, scenarios: SCEN }, null, 1) + "\n");
const md = ["# Headless-sim sample — POI templates vs the 12-minute breach floor", "",
  `Generated by \`tools/living-world/sim_sample.mjs\` (N = ${N} seeded POIs per archetype, real \`server/sim\` kernel, dt ${DT}s, cap ${FLOOR_SEC / 60} min). Deterministic — re-running gives the same table.`, "",
  "Model: the POI's threat scales the defending core (×0.5–×2.5) and garrison; garrison units hold ground (leashed); neutral camps act as third-party barbarians; the attacker is the stock bot hero + minion waves (≈ an even-strength attacker, i.e. *weaker* than the doc-03 1.5× floor case).", "",
  "| Archetype | n | Breached ≤ 12 min | Median breach | Median threat | Median attacker losses | Defender wins | Verdict |", "|---|---|---|---|---|---|---|---|",
  ...rows.map((r) => `| ${r.k} | ${r.n} | ${r.breachRate} % | ${r.medBreachSec != null ? Math.floor(r.medBreachSec / 60) + ":" + String(r.medBreachSec % 60).padStart(2, "0") : "—"} | ${r.medThreat} | ${r.medAttackerDeaths} | ${r.defenderWins} | ${r.flag} |`), "",
  (() => { const c = rows.find((r) => r.k === "CALIBRATION"); const ok = c && c.breachRate === 100 && c.medBreachSec >= 360 && c.medBreachSec <= 720;
    return `**Calibration:** a bare castle (threat 50, S2 structures: 8 walls 1,350 HP, 2 gates 1,150 HP, 2 castle towers 2,350 HP, keep 2,400 × tier; structure HP ×${DEF_MUL}) vs the floor-case attacker (1.5× squad, ⅓ canon SIEGE ×6 vs structures, + waves) breaches at **${c && c.medBreachSec != null ? Math.floor(c.medBreachSec / 60) + ":" + String(c.medBreachSec % 60).padStart(2, "0") : "—"}** — ${ok ? "inside the 6–12 min target band ✅" : "OUTSIDE the 6–12 min target band ❌"}.`; })(), "",
  "## Defences (doc 03) and Guardians (doc 04) on the calibration castle", "",
  "| Scenario | Breached (≤ 12 min; Guardian rows ≤ 25 min) | Median breach | Median attacker losses | Guardian KO'd | Median Guardian KO time | Guardian HP left at the end |", "|---|---|---|---|---|---|---|",
  ...["BASE", "DEFENDED", "F2", "F3"].map((sc) => { const r = SCEN.filter((x) => x.scen === sc), b = r.filter((x) => x.breached), ko = r.filter((x) => x.guardianKoSec != null), mb = med(b.map((x) => x.sec)), mk = med(ko.map((x) => x.guardianKoSec));
    const f = (v) => v != null ? Math.floor(v / 60) + ":" + String(v % 60).padStart(2, "0") : "—";
    return `| ${{ BASE: "Bare castle", DEFENDED: "Fully upgraded (×1.6 cap; attacker 1.5× the defence-weighted garrison)", F2: "+ Form 2 Warden", F3: "+ Form 3 Ascendant (5 % dmg for 8 min, then tires to 40 %)" }[sc]} | ${Math.round(100 * b.length / r.length)} % | ${f(mb)} | ${med(r.map((x) => x.attackerDeaths))} | ${sc === "F2" || sc === "F3" ? ko.length + "/" + r.length : "—"} | ${sc === "F2" || sc === "F3" ? f(mk) : "—"} | ${sc === "F2" || sc === "F3" ? med(r.map((x) => x.guardianHpPct)) + " %" : "—"} |`; }), "",
  "Tuning rule (doc 02 §5): an archetype out of band is re-tuned in `poi-archetypes.json` (garrison / threat curve), never per map.", ""].join("\n");
fs.writeFileSync(OUT, md);
console.log(md);
